language: go
go: "1.13.x"


jobs:
  - env: TEST_ARGS="-race -short"
  - env: TEST_ARGS="-bench . -benchmem -benchtime 30s -run=^$"
  - env: TEST_ARGS="-coverprofile=coverage.txt -covermode=atomic"
    before_install:
      - sudo apt-get -y install python3
    before_script:
      - mkdir ./testdata/gen
      - python3 ./tools/testgenerator.py --csv testdata/gen/tc_wr_mil_few_async.csv --add 1000000 jump run sit stand
    after_success: 
      - go tool cover -func coverage.txt
      - bash <(curl -s https://codecov.io/bash)

script: "go test -v $TEST_ARGS"
