language: go
go: "1.13.x"

env:
  - TEST_ARGS="-race"
  - TEST_ARGS="-coverprofile=coverage.txt -covermode=atomic"

before_install:
  - sudo apt-get -y install python3

before_script:
  - mkdir ./testdata/gen
  - python3 ./tools/testgenerator.py --csv testdata/gen/tc_mil_few_async.csv --add 1000000 jump run sit stand

script: "go test $TEST_ARGS"

after_success:
  - bash <(curl -s https://codecov.io/bash)
